config/routes.rb
Finalproject::Application.routes.draw do
  
  root "welcome#index"
  resources :posts
  resources :users

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3}
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts

  validates :name, presence: true, length: {minimum: 3} 
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :user_signed_in

  private

    def current_user
      User.find(session[:user_id]) if session[:user_id]
    end

    def user_signed_in?
      current_user.present?
    end

    def require_authentication
      if current_user.nil?
        redirect_to signin_url(return_to: request.url), notice: "Please sign in"
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_authentication, except: [:show, :index]
  before_action :set_post, only: [:show, :update, :edit, :destroy]

  def index
    @posts = Post.order('created_at DESC').page(params[:page]).per(2)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Post has been created!'
    else
      flash[:alert] = 'Post has not been created.'
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    
    if @post.update(post_params) && @post.user == current_user
    redirect_to @post, notice: 'Post has been updated.'
    else
      flash[:alert] = 'Post has not been updated.'
      render 'edit'
    end
  end

  def destroy
    if @post.user == current_user
      @post.destroy

      redirect_to posts_path, notice: 'Post has been deleted!'
    else
      redirect_to posts_path, alert: 'You are not authorized'
    end
  end
  
  private

    def post_params
      params.require(:post).permit(:title, :content)
    end

    def set_post
      @post = Post.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to posts_path, alert: "The post you were looking for could not be found."
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(email: params[:signin][:email]).first

    if user && user.authenticate(params[:signin][:password])
      session[:user_id] = user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_url
    else
      flash[:error] = "Sorry."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed out succesfully."

    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "You have signed up successfully!"
    else
      flash[:alert] = "You have not signed up"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/_messages.html.erb
<% flashes = {notice: 'success', alert: 'standard', error: 'alert', secondary: 'secondary'} %>
<% flashes.each do |key, value| %>
  <% if flash[key] %>
    <p><%= content_tag :div, :data => { :alert => '' }, :class => "alert-box #{value} radius" do %>
      <%= flash[key] %>
      <%= link_to '&times;'.html_safe, '#', :class => 'close'%>
    <% end %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= @title || 'My Blog' %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

      <nav class="top-bar">
        <ul class="title-area">
          
          <!-- Title Area -->
          <li class="name">
            <h1><%= link_to 'Hello World! BLOG', root_path %></h1>
          </li>
          
          <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon">
            <a href="#"><span>Menu</span></a>
          </li>
        
        </ul>

        <section class="top-bar-section">
          <!-- Left Nav Section -->
          <ul class="left">
            <li class="divider"></li>
            <li class="active"><%= link_to 'Posts', posts_path %></li>
            <li class="divider"></li>
            <% if current_user %>
            <li ><%= link_to 'Create new post!', new_post_path, class: 'button medium radius' %></li>
            <% end %>
            <li class="divider"></li>
            
          </ul>

          <!-- Right Nav Section -->
          <ul class="right">
            <li class="divider hide-for-small"></li>
       
            <li class="divider show-for-small"></li>
              
            <% if current_user %>
              <li class="divider"></li>
              <li>
                <%= link_to "Signed in as #{current_user.email}", user_path(current_user) %>
              </li>
              <li class="has-form">
                <%= link_to "Sign out", signout_path, method: :delete, class: "button radius" %>
               <!--  <a class="button" href="#">Log In!</a> -->
              </li>
            <% else %>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign up", new_user_path %>
              </li>
              <li class="has-form">
                <%= link_to "Sign in", signin_path, class: "button radius" %>
               <!--  <a class="button" href="#">Log In!</a> -->
              </li>
            <% end %>
          </ul>
        </section>
      </nav>

 
       <div class="row">

        <%= render 'layouts/messages' %>

       

          <%= yield %>


      </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

    

app/views/posts/_errors.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert-box radius alert">
    <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved
    </div>
  </div>

  <div id="error_explanation">
    <div class="alert-box radius alert">
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<div class='panel'><%= form_for @post do |p| %>
  <%= render 'errors' %>

  <%= p.label :title %><br>
  <%= p.text_field :title %>
  <%= p.label :content %><br>
  <%= p.text_area :content %>
  <%= p.submit class: "button medium radius" %>
<% end %></div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
  <div class="row">
 
    <div class="large-12 columns" role="content">
 
      <article>
              <% @posts.each do |post| %>
       
              <h3><%= link_to post.title, post_path(post) %></h3>
              <h6>Written by <%= link_to post.user.name, user_path(post.user) %> on <%= post.created_at.strftime("%m/%d/%Y") %></h6>
       
                <p><%= truncate (post.content), length: 400, omission: (link_to '... (continued)', post_path(post)), escape: false %></p>
       
            </article>
 
      <hr />

        <% end %>
       <%= paginate @posts %>
    </div>
 

app/views/posts/new.html.erb
<div class='small-8 large-centered columns'><h2>New Project</h2>
<%= render 'form' %></div>

app/views/posts/show.html.erb
<% @title = @post.title %>
<div class="large-10 columns large-centered"><h2><%= @post.title %></h2>

<div class="panel">
<h5>Written by <%= link_to @post.user.name, user_path(@post.user) %> on <%= @post.created_at.strftime("%m/%d/%Y")  %></h5>
  <p><%= @post.content %></p>

<% if current_user == @post.user %>

<p><%= link_to 'Edit post', edit_post_path(@post), class: 'button medium radius' %>
  <%= link_to 'Delete Post', post_path(@post), 
                            method: :delete, 
                            data: {confirm: 'Are you sure?'}, class: 'button medium radius alert' %></p>
<% end %></div></div>

app/views/users/_form.html.erb
<div class='panel'><%= form_for @user do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
</p>
<p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</p>
<p>
  <%= f.submit "Sign up!", class: 'button medium radius'%>
</p></div>
<% end %>

app/views/users/new.html.erb
<div class="large-8 columns large-centered"><h1>Sign up!</h1>

<%= render 'form' %>
</div>

app/views/users/show.html.erb
<h4>Posts by <%= @user.name %> contact at <%= @user.email %></h4>


<ol>
  <% @user.posts.each do |p| %>
  <li><%= link_to p.title, post_path(p) %> - <%= truncate p.content %><%= p.created_at.strftime("%m/%d/%Y") %> </li>
  <% end %>
</ol>

app/views/welcome/index.html.erb
<h1>Hello World</h1>

<p>This is <%= link_to 'My Blog', posts_path %>, I hope that you enjoy it as much as I do</p>